//neha kakkar
import lalala from "../songs/kakkar/lalala.mp3";
import manvalage from "../songs/kakkar/manvalage.mp3";
import milehotum from "../songs/kakkar/milehotum.mp3";
import niklecurrent from "../songs/kakkar/niklecurent.mp3";
import sorry from "../songs/kakkar/sorry.mp3";
//kk
import Ajabada from "../songs/kk/ajabada.mp3";
import Dilibaadat from "../songs/kk/dilibaadat.mp3";
import Labonko from "../songs/kk/laboko.mp3";
import Teriyaadomain from "../songs/kk/teriyaadomain.mp3";
import Tuhi from "../songs/kk/tuhimerasab.mp3";
//arjit
import Humdard from "../songs/Humdard.mp3";
import Ikvaariaa from "../songs/Ikvaariaa.mp3";
import Illhi from "../songs/Illahi.mp3";
import Jaanisar from "../songs/Jaannisaar.mp3";
import Omaahi from "../songs/Omaahi.mp3";
import Qaafirana from "../songs/Qaafirana.mp3";
import Spotify from '../images/spotifylogo.png';
const searchData = [
  {
    snumber: 1,
    title: "Lalala",
    src: lalala,
    Artist1: "Neha kakkar",
    popularity: "231,802,116",
    time: "4:19",
    logo: Spotify,
  },
  {
    snumber: 2,
    title: "Manva laage",
    src: manvalage,
    Artist1: "Neha kakkar",
    popularity: "231,802,116",
    time: "4:19",
    logo: Spotify,
  },
  {
    snumber: 3,
    title: "Mile ho tum",
    src: milehotum,
    Artist1: "Neha kakkar",
    popularity: "231,802,116",
    time: "4:19",
    logo: Spotify,
  },
  {
    snumber: 4,
    title: "Nikkle Current",
    src: niklecurrent,
    Artist1: "Neha kakkar",
    popularity: "231,802,116",
    time: "4:19",
    logo: Spotify,
  },
  {
    snumber: 5,
    title: "Sorry",
    src: sorry,
    Artist1: "Neha kakkar",
    popularity: "231,802,116",
    time: "4:19",
    logo: Spotify,
  },
  {
    snumber: 6,
    title: "Ajab Ada",
    src: Ajabada,
    Artist1: "Neha kakkar",
    popularity: "231,802,116",
    time: "4:19",
    logo: Spotify,
  },
  {
    snumber: 7,
    title: "Dilibaadat",
    src: Dilibaadat,
    Artist1: "Arijit singh",
    popularity: "231,802,116",
    time: "4:19",
    logo: Spotify,
  },
  {
    snumber: 8,
    title: "Labon ko",
    src: Labonko,
    Artist1: "Krishan Kumar",
    popularity: "231,802,116",
    time: "4:19",
    logo: Spotify,
  },
  {
    snumber: 9,
    title: "Teri Yaado mai",
    src: Teriyaadomain,
    Artist1: "Krishan Kumar",
    popularity: "231,802,116",
    time: "4:19",
    logo: Spotify,
  },
  {
    snumber: 10,
    title: "tuhi mera sab",
    src: Tuhi,
    Artist1: "Krishan Kumar",
    popularity: "231,802,116",
    time: "4:19",
    logo: Spotify,
  },
  {
    snumber: 11,
    title: "Humdard",
    src: Humdard,
    Artist1: "Arijit Singh",
    popularity: "231,802,116",
    time: "4:19",
    logo: Spotify,
  },
  {
    snumber: 12,
    title: "Ik Vaari Aa",
    src: Ikvaariaa,
    Artist1: "Arijit Singh",
    popularity: "231,802,116",
    time: "4:19",
    logo: Spotify,
  },
  {
    snumber: 13,
    title: "Ilaahi",
    src: Illhi,
    Artist1: "Neha kakkar",
    popularity: "231,802,116",
    time: "4:19",
    logo: Spotify,
  },
  {
    snumber: 14,
    title: "Jaanisar",
    src: Jaanisar,
    Artist1: "Neha kakkar",
    popularity: "231,802,116",
    time: "4:19",
    logo: Spotify,
  },
  {
    snumber: 15,
    title: "O Maahi",
    src: Omaahi,
    Artist1: "Arijit Singh",
    popularity: "231,802,116",
    time: "4:19",
    logo: Spotify,
  },
  {
    snumber: "16",
    title: "Qaafirana",
    src: Qaafirana,
    Artist1: "Arijit Singh",
    popularity: "231,802,116",
    time: "4:19",
  }, 
  // {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // }, {
  //   snumber: "6",
  //   title: "Ajab Ada",
  //   src: Ajabada,
  //   Artist1: "Neha kakkar",
  //   popularity: "231,802,116",
  //   time: "4:19",
  // },
];

export default searchData;
